import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import trapezoid

## Parse files generated by running nodeRemoval_50networksPerEcosystem.py
Bnetworks=sorted([File for File in os.listdir('.') if File.endswith('.csv') and File.startswith('nodeRemoval_')])
Fnetworks=sorted([File for File in os.listdir('.') if File.endswith('.csv') and File.startswith('nodeRemoval_')]) 

fig,ax=plt.subplots(1,4,figsize=(20,5),width_ratios=(1.5,0.5,1.5,0.5))
dfs=[]

## Parse results, calculate AUCs and plot data for bacteria
AUCs_bac=[]
for network in Bnetworks:
    env=network.split('_')[-1].split('.')[0]
    df=pd.read_csv(network)
    df['Network']=network
    df['Environment']=env
    df['Organisms']='Bacteria'
    dfs.append(df)
    AUCs_bac.append({'AUC':trapezoid(y=df['Reduction in density (in %)'], x=df['Number of attacked nodes']),
                 'Environment':env,
                 'Network':network,       
                })
AUCs_bac=pd.DataFrame(AUCs_bac)

## Parse results, calculate AUCs and plot data for fungi
AUCs_fun=[]   
for network in Fnetworks:
    env=network.split('_')[-1].split('.')[0]
    df=pd.read_csv(network)
    df['Network']=network
    df['Environment']=env
    df['Organisms']='Fungi'
    dfs.append(df)
    AUCs_fun.append({'AUC':trapezoid(y=df['Reduction in density (in %)'], x=df['Number of attacked nodes']),
                 'Environment':env,
                 'Network':network,       
                })
AUCs_fun=pd.DataFrame(AUCs_fun)

df=pd.concat(dfs)

## Plot figure
palette={'Cropland':'#ffd237','Grassland':'#73dc5c','Woodland':'#f88a22'}
palette2={'Cropland':'#ffffb3','Grassland':'#ccebc5','Woodland':'#fdc086'}
flierprops = dict(marker='o', markerfacecolor='black', markersize=1,linestyle='none')
sns.lineplot(data=df[df['Organisms']=='Fungi'],x='Number of attacked nodes',y='Reduction in density (in %)',hue='Environment',ax=ax[2],palette=palette)
sns.lineplot(data=df[df['Organisms']=='Bacteria'],x='Number of attacked nodes',y='Reduction in density (in %)',hue='Environment',ax=ax[0],palette=palette)
sns.boxplot(data=AUCs_bac,x='Environment',y='AUC',ax=ax[1],palette=palette2,flierprops=flierprops)
sns.boxplot(data=AUCs_fun,x='Environment',y='AUC',ax=ax[3],palette=palette2,flierprops=flierprops)
bottom, top=ax[1].get_ylim()
ax[1].set_ylim(bottom, top+((top-bottom)/10))
bottom, top=ax[3].get_ylim()
ax[3].set_ylim(bottom, top+((top-bottom)/10))
plt.savefig('nodeRemoval_50networksPerEcosystem.pdf')
plt.close()
